// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleEmployeeApp.Models.DataLayer;

#nullable disable

namespace SimpleEmployeeApp.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20221228082022_ApplyConfiguration")]
    partial class ApplyConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpleEmployeeApp.Models.DomainModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("dateOfBirth")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("middleInitial")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("socialSecurityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            address = "3322 Davis Street Carnesville, GA 30521",
                            dateOfBirth = new DateTime(1985, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "Peter",
                            lastName = "Rowan",
                            middleInitial = "E.",
                            socialSecurityNumber = "671-24-6875"
                        },
                        new
                        {
                            Id = 2,
                            address = "169 Breezewood Court Coolidge, KS 67836",
                            dateOfBirth = new DateTime(1957, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "Randall",
                            lastName = "Hatfield",
                            middleInitial = "W.",
                            socialSecurityNumber = "513-12-4682"
                        },
                        new
                        {
                            Id = 3,
                            address = "3455 Dancing Dove Lane New York, NY 10011",
                            dateOfBirth = new DateTime(1991, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "Casey",
                            lastName = "Foster",
                            middleInitial = "A.",
                            socialSecurityNumber = "069-34-5134"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
